- src/api/chainHead_unstable_call.md
Fixes one of the remaining TODOs
I went for mimicking the existing `state_call` function: https://polkadot.js.org/docs/substrate/rpc/#callmethod-text-data-bytes-at-blockhash-bytes
> Accept one value only for `callParameters`

- src/api/chainHead_unstable_call.md
It doesn't seem necessary to actually error if a host function with side effects is called.
This also makes the new API more easy to implement on Substrate, which already has all the APIs to ignore side effects but not the APIs to return errors.
> Allow side effects in chainHead_unstable_call

- .github/dependabot.yml
- .github/workflows/book.yml
In order to improve our security posture with GitHub Actions usage. I've made a version pinning ether to commit hash or to specific version.
Additionally added `dependabot` to track GHA version changes.
Related issues and policy:
https://github.com/paritytech/ci_cd/issues/114
https://github.com/paritytech/ci_cd/issues/464
https://github.com/paritytech/ci_cd/wiki/Policies-and-regulations:-GitHub-Actions-usage-policies
> Pin GHA versions and add dependabot

- src/api/chainHead_unstable_storage.md
- src/api/chainHead_unstable_storageContinue.md
Close https://github.com/paritytech/json-rpc-interface-spec/issues/21
Even though they're unrelated, this PR is based on top of https://github.com/paritytech/json-rpc-interface-spec/pull/35. I expect https://github.com/paritytech/json-rpc-interface-spec/pull/35 to be merged, and didn't want to have conflicts.
This PR enhances `chainHead_unstable_storage` by adding back the `type` field that was removed in #17.
You can now query not just the value of a storage item, but also the hash of its value, the values of the item and all its descendants, the hashes of item and all its descendants, or the Merkle value of the item or its closest ancestor.
Querying the descendants of the storage item makes it possible to enumerate all the keys under a certain prefix, which is important to know the …
> Make `chainHead_unstable_storage` more powerful

- src/api/chainHead_unstable_storage.md
Close #48
Close #47
This complicates the API quite a bit, and a lot of subtle details needed to change in order for this to work:
- In the case of a closest descendant Merkle value, we must now provide the original `key` in order to avoid ambiguities when you request the closest descendant Merkle value of multiple items at the same time.
- No error is generated anymore if the trie is empty and you request the closest descendant Merkle value. Instead there's no result now. This complicates a bit the JSON-RPC client code (which is why an error was thrown originally) but is necessary for multiple items to work.
- The server is allowed to return duplicate information, because it might not be possible for the server to de-duplicate information without using tons of memory, while the JSON-RPC …
> Allow querying and returning multiple items at once in `chainHead_unstable_storage`

- src/api/chainHead_unstable_storage.md
When you query a `closest-ancestor-merkle-value`, it is possible that the `key` doesn't have any ancestor.
It is not something I have considered, because in practice there's always a trie node whose key is `[]` (empty), and so every key always has an ancestor. But in theory this is not necessarily true. Some chains might not have any trie node at `[]`.
I have additionally clarified the fact that for `value` and `hash` the result doesn't contain any item about a key if the trie doesn't contain a storage value associated to said `key`.
> Clarify behaviour of `chainHead_unstable_storage`

- src/api/chainHead_unstable_storage.md
Amends #54 
Determining which key corresponds to `merkle-value` requires asking for more data on the networking than necessary otherwise, so I would suggest to remove this field.
> Remove `merkle-value-key` field

- src/api/chainHead_unstable_call.md
I'm pretty sure that this was a copy/paste mistake as non of the other `inaccessble` events have the `error` property. Also, IMO it doesn't make a lot of sense to have an error property on this event.
cc: @tomaka
> fix: `inaccessible` event on `chainHead_unstable_call`

- src/api/chainHead_unstable_storage.md
Close #25 
Translated in layman terms, this basically means "this works the same way as everything else in Substrate/Polkadot". Doing it differently would add a lot of surprise factor.
> Clarify behaviour w.r.t. child tries in main trie

- src/api/chainHead_unstable_body.md
- src/api/chainHead_unstable_call.md
- src/api/chainHead_unstable_storage.md
I think that I've accidentally removed this detail in the previous PR.
Note that the `unpin` function already says the same thing. This PR doesn't change anything, it's just to clarify.
> Clarify unpin behaviour

- src/api/chainHead.md
- src/api/chainHead_unstable_body.md
- src/api/chainHead_unstable_call.md
- src/api/chainHead_unstable_continue.md
- src/api/chainHead_unstable_follow.md
- src/api/chainHead_unstable_storage.md
This changes all related events from the kebab-case naming convention to camelCase.
Closes: https://github.com/paritytech/json-rpc-interface-spec/issues/74
// cc @tomaka @josepot @jsdw
> chainHead: Standardize `camelCase` for reported events

- src/SUMMARY.md
- src/api/chainHead_unstable_genesisHash.md
Since the objective is to stabilize the `chainHead` namespace in the nearby future, this pull request proposes to remove the `chainHead_unstable_genesisHash` JSON-RPC function out of caution.
The reason is that a client that simply follows the head of the chain might not necessarily be aware of what the genesis hash is. See https://github.com/polkadot-fellows/RFCs/pull/8 for an example.
The genesis hash can be found in the chain at `System::BlockHash[0]`, but since this is a runtime-specific thing it should be implemented by the JSON-RPC client on top of `chainHead_storage`, rather than by the server.
Note that `archive_genesisHash` and `chainSpec_genesisHash` still exist, as a node that implements `archive` is clearly supposed to know what the genesis hash is, and that a node that …
> Remove `chainHead_unstable_genesisHash`

- src/api.md
- src/api/chainHead_unstable_follow.md
- src/api/chainHead_unstable_storage.md
Closes: https://github.com/paritytech/json-rpc-interface-spec/issues/88
> Specify merkle value

- src/api/transaction_unstable_submitAndWatch.md
Closes #83
/cc @tomaka @josepot @lexnv
> Use integer, not string for block index in `chainHead_follow` events

- src/api/archive_unstable_storageContinue.md
- src/api/chainHead_unstable_follow.md
For consistency with generated events, the `waiting-for-continue`
description is now using camalCase convention.
cc @tomaka @jsdw @josepot @paritytech/subxt-team
> archive: Use camelCase for waitingForContinue event

- src/api/archive_unstable_finalizedHeight.md
- src/api/archive_unstable_hashByHeight.md
This PR changes the return value and parameters from using a string containing an integer to a plain integer.
This change reflects: https://github.com/paritytech/json-rpc-interface-spec/pull/84
cc @tomaka @jsdw @josepot @paritytech/subxt-team
> archive: Use integer for describing block height

- src/api/archive_unstable_body.md
- src/api/archive_unstable_hashByHeight.md
- src/api/archive_unstable_storage.md
- src/api/chainHead_unstable_body.md
- src/api/chainHead_unstable_storage.md
This PR uses the same description for the `hash` parameter as the one from the `chainHead`.
cc @tomaka @jsdw @josepot @paritytech/subxt-team
> archive/body: Keep description consistent with chainHead

- src/api/rpc_methods.md
Just a tiny clarification to address this sort of thing https://github.com/paritytech/polkadot-sdk/issues/1627.
The spec does already say "all names", but I thought it'd be good to emphasise this particular point
> Tiny clarification in rpc_methods

- src/api/chainHead_unstable_unpin.md
This PR renames the parameter of the unpin method from `hash` to `hash_or_hashes` to suggest to the users that it can be one of two different formats: plain hex or array of hexes.
Another approach to clarify this would be to change the `hash` parameter to `hashes` and accept only an array of hex-encoded hashes. 
// cc @paritytech/subxt-team @josepot @tomaka
> chainHead/unpin: Explicit about unpin parameters

- src/grouping-functions-and-node-capabilities.md
The description for archive nodes was missing.
> Add archive node description

- src/api/chainHead_unstable_body.md
- src/api/chainHead_unstable_call.md
- src/api/chainHead_unstable_continue.md
- src/api/chainHead_unstable_follow.md
- src/api/chainHead_unstable_header.md
- src/api/chainHead_unstable_storage.md
- src/api/chainHead_unstable_unpin.md
This PR defined the error codes returned by the server:
- `-32800` two or more subscriptions requested for chainHead_follow
- `-32801` block hash not reported by chainHead_follow or block hash has been unpinned
- `-32802` chainHead_follow started with withRuntime == false
- `-32803` chainHead_follow did not generate an operationWaitingForContinue event
The following are errors defined in the [JSON-RPC spec](https://www.jsonrpc.org/specification#error_object):
- `-32602` The provided parameter isn't one of the expected values, has different format or is missing
- `-32603` Internal server error:
- The server was unable to generate a valid subscription ID (https://github.com/paritytech/polkadot-sdk/blob/21f1811c6600d8a7fe043592ff34dcb79284d583/substrate/client/rpc-spec-v2/src/chain_head/chain …
> chainHead: Define error codes returned by the server

- src/api/chainHead_unstable_follow.md
> docs: improve `operationInaccessible` event

- src/SUMMARY.md
- src/api/sudo_network_unstable_unwatch.md
- src/api/sudo_network_unstable_watch.md
This is a revival of https://github.com/paritytech/smoldot/issues/2245
This new function lets the JSON-RPC client subscribe to the networking state of the server, which allows visualizing what is happening, which in turn should be useful for debugging and teaching purposes.
One opinionated decision I took is that the JSON-RPC server might omit some events if the events are generated too quickly. For example, if a peer-to-peer connection opens then closes repeatedly 1000 times per second, we don't have to send 2000 events per second to the JSON-RPC client and instead we're allowed to not send anything.
This means that the JSON-RPC client might not be aware of everything that's happening. There's an event to notify it when that happens so that a warning or something can be shown to the …
> Add `sudo_network_unstable_watch`

- src/api/chainHead_unstable_unpin.md
This PR clarifies the behavior of the server when the `chainHead_unpin` receives duplicate hashes.
When duplicate hashes are received as parameters, the server returns `-32804`.
Likewise, the server could return the `-32602` for invalid parameters. However, I thought a dedicated error would provide clear details to the user wrt what needs to be changed. This felt appropriate since we also have a dedicated error for `withRuntime` flag:
> `-32802` is generated if the `followSubscription` corresponds to a follow where `withRuntime` was `false`.
cc @paritytech/subxt-team 
cc: https://github.com/paritytech/polkadot-sdk/pull/3313#discussion_r1488492795
Closes: https://github.com/paritytech/json-rpc-interface-spec/issues/133
> chainHead/unpin: Return error on duplicate hashes

- src/api/transactionWatch_unstable_submitAndWatch.md
This PR removes the `Broadcasted` event from the `transactionWatch` and the `broadcasted` field from the `Dropped` event.
The `Broadcasted` event was introduced to inform users about the transaction process.
However, the number of peers it contains does not offer any strong guarantees about the uniqueness of those peers; or if the transaction could be later included in the chain by those peers.
Further, the `Broadcasted` event is hard to enforce by load balancers; in cases where the server goes down without sending a `Broadcasted` event first.
I would love to get your thoughts on this 
Closes https://github.com/paritytech/json-rpc-interface-spec/issues/132.
cc @paritytech/subxt-team
> transactionWatch: Remove the broadcast event

- src/api/sudo_network_unstable_unwatch.md
It is right now not mentioned what happens in that situation
> Return an error if sudo_network_unstable_unwatch is passed a wrong ID

- src/SUMMARY.md
- src/api/transactionWatch_unstable_unwatch.md
- src/api/transactionWatch_v1_submitAndWatch.md
- src/api/transactionWatch_v1_unwatch.md
- src/dos-attacks-resilience.md
This PR stabilizes the following methods:
- `transactionWatch_unstable_submitAndWatch` -> `transactionWatch_v1_submitAndWatch`
- `transactionWatch_unstable_unwatch` -> `transactionWatch_v1_unwatch`
Opened this PR to discuss the best path forward for `transactionWatch`.
We had different views about this method class on https://github.com/paritytech/json-rpc-interface-spec/pull/139, and would love to get your feedback on this 🙏 
cc @paritytech/subxt-team @tomaka @josepot
> Stabilize `transactionWatch` to version 1

- src/SUMMARY.md
- src/api/transactionWatch_unstable_submitAndWatch.md
- src/api/transactionWatch_unstable_unwatch.md
- src/dos-attacks-resilience.md
I can't easily edit fork PRs, so I made this to resolve the merge conflict and enact #144
> Revert "Stabilize `transactionWatch` to version 1"

- src/api/transactionWatch_unstable_submitAndWatch.md
This PR is a followup of the proposal from: https://github.com/paritytech/json-rpc-interface-spec/pull/150#pullrequestreview-1988787293
In this PR, the concept of limits is removed from the `transactionWatch`, as noted in: https://github.com/paritytech/json-rpc-interface-spec/pull/150.
- Servers can still return `Transaction::Dropped` if the node cannot keep up with the number of transactions (as per spec), however servers are not required to support a minimum of 4 subscriptions per client
cc @paritytech/subxt-team @tomaka
> txWatch: Remove the txWatch limits

- src/SUMMARY.md
- src/api/transactionWatch_v1_submitAndWatch.md
- src/api/transactionWatch_v1_unwatch.md
- src/dos-attacks-resilience.md
This PR stabilizes the `transactionWatch` class of APIs.
Depends on: https://github.com/paritytech/json-rpc-interface-spec/pull/153.
cc @paritytech/subxt-team @tomaka
> txWatch: Stabilize to version 1

- src/api/archive_unstable_stopStorageDiff.md
- src/api/archive_unstable_storageDiff.md
This PR modifies the `archive_unstable_storageDiff` as a subscription instead of a method.
The change mainly leverages subscriptions' backpressure without implementing a low-level API by the RPC crates. 
This is a followup from: 
- https://github.com/paritytech/json-rpc-interface-spec/issues/160
cc @paritytech/subxt-team
> archive: Use subscriptions for `storageDiff` 
